/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.rm.veiw;

import br.rm.controle.Repository;
import br.rm.controle.Validacao;
import br.rm.modelo.Rm_Cliente;
import br.rm.modelo.Rm_Colaborador;
import static br.rm.veiw.Inicio.jDesktopPane;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Jayne
 */
public class ClienteCadastro extends javax.swing.JInternalFrame {

    private StringBuilder erros;
    private Rm_Colaborador colaborador;
    private String operacao;
    private Rm_Cliente cliente;
    DefaultListModel modelo;
    List<Rm_Cliente> clienteList;

    public ClienteCadastro(Rm_Colaborador colaborador) {
        initComponents();
        this.operacao = "CRIAR";
        jListCliente.setVisible(false);
        modelo = new DefaultListModel();
        jListCliente.setModel(modelo);
        this.colaborador = colaborador;
        setFrameIcon(new ImageIcon(getClass().getResource("/icons/usuario.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTNomeComercio = new br.rm.controle.JTextFieldHint(new JTextField(), "Nome do Comércio");
        ;
        jTNumeroComercio = new br.rm.controle.JTextFieldHint(new JTextField(), "Número");
        ;
        jTRuaComercio = new br.rm.controle.JTextFieldHint(new JTextField(), "Rua");
        ;
        jTBairroComercio = new br.rm.controle.JTextFieldHint(new JTextField(), "Bairro"

        );
        ;
        jTCnpj = new br.rm.controle.JTextFieldHint(new JTextField(), "CNPJ - 00.000.000/0001-00");
        ;
        jPanel1 = new javax.swing.JPanel();
        jTRua = new br.rm.controle.JTextFieldHint(new JTextField(), "Rua");
        ;
        jTNumero = new br.rm.controle.JTextFieldHint(new JTextField(), "Número");
        ;
        jTCep = new br.rm.controle.JTextFieldHint(new JTextField(), "CEP");
        ;
        jTBairro = new br.rm.controle.JTextFieldHint(new JTextField(), "Bairro"

        );
        ;
        jPanel3 = new javax.swing.JPanel();
        jTNome = new br.rm.controle.JTextFieldHint(new JTextField(), "Nome");
        ;
        jTCpf = new br.rm.controle.JTextFieldHint(new JTextField(), "CPF - 000.000.000-00");
        ;
        jTRg = new br.rm.controle.JTextFieldHint(new JTextField(), "RG");
        ;
        jTCelular = new br.rm.controle.JTextFieldHint(new JTextField(), "Celular");
        ;
        jTRecado = new br.rm.controle.JTextFieldHint(new JTextField(), "Tel Recado");
        ;
        jTDataNascimento = new br.rm.controle.JTextFieldHint(new JTextField(), "Data Nasc. - DD/MM/AAAA");
        ;
        jTEmail = new br.rm.controle.JTextFieldHint(new JTextField(), "Email");
        ;
        jListCliente = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Cadastrar e editar clientes");

        jBSalvar.setBackground(new java.awt.Color(51, 51, 51));
        jBSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBSalvar.setText("Salvar");
        jBSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBSalvar.setFocusPainted(false);
        jBSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSalvarMouseExited(evt);
            }
        });
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados do comércio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jTNomeComercio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTNomeComercio.setForeground(new java.awt.Color(255, 255, 255));

        jTNumeroComercio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTNumeroComercio.setForeground(new java.awt.Color(255, 255, 255));

        jTRuaComercio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTRuaComercio.setForeground(new java.awt.Color(255, 255, 255));
        jTRuaComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRuaComercioActionPerformed(evt);
            }
        });

        jTBairroComercio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTBairroComercio.setForeground(new java.awt.Color(255, 255, 255));

        jTCnpj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTCnpj.setForeground(new java.awt.Color(255, 255, 255));
        jTCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTCnpjFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTNumeroComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNomeComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTBairroComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTRuaComercio))
                        .addGap(31, 31, 31))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRuaComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBairroComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jTNumeroComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jTRua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTRua.setForeground(new java.awt.Color(255, 255, 255));

        jTNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTNumero.setForeground(new java.awt.Color(255, 255, 255));

        jTCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTCep.setForeground(new java.awt.Color(255, 255, 255));
        jTCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCepActionPerformed(evt);
            }
        });

        jTBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTBairro.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCep, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dados pessoais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jTNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTNome.setForeground(new java.awt.Color(255, 255, 255));
        jTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTNomeKeyPressed(evt);
            }
        });

        jTCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTCpf.setForeground(new java.awt.Color(255, 255, 255));
        jTCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTCpfFocusLost(evt);
            }
        });

        jTRg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTRg.setForeground(new java.awt.Color(255, 255, 255));

        jTCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTCelular.setForeground(new java.awt.Color(255, 255, 255));

        jTRecado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTRecado.setForeground(new java.awt.Color(255, 255, 255));

        jTDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        jTDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTDataNascimentoFocusGained(evt);
            }
        });

        jTEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTEmail.setForeground(new java.awt.Color(255, 255, 255));

        jListCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jListCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTRg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRecado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jListCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRecado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalvarMouseEntered
        jBSalvar.setBackground(new Color(153, 153, 0));
        jBSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBSalvarMouseEntered

    private void jBSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalvarMouseExited
        jBSalvar.setBackground(new Color(51, 51, 51));
        jBSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBSalvarMouseExited

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        if (operacao.equals("CRIAR")) {
            criarCliente();
        }
        if (operacao.equals("EDITAR")) {
            atualizarCliente(cliente);
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jTRuaComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRuaComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRuaComercioActionPerformed

    private void jTCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCepActionPerformed

    private void jTCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCpfFocusLost

        if (!new Validacao().validarCPF(jTCpf.getText())) {
            JOptionPane.showMessageDialog(null, "CPF INVALIDO", "CPF INVALIDO", WIDTH);
            jTCpf.requestFocus();
        } else {

            cliente = Repository.getInstance().buscarClientePorCpf(jTCpf.getText().trim().replaceAll("[^0-9]", ""));
            if (cliente != null) {
                int resposta = JOptionPane.showConfirmDialog(null, "CPF JÁ CADASTRADO Deseja EDITAR as informaçoes?", "Confirmação", JOptionPane.YES_NO_OPTION);

                switch (resposta) {
                    // Ação a ser executada caso o usuário clique em "Sim"
                    case JOptionPane.YES_OPTION:
                        carregarFormulario(cliente);
                        operacao = "EDITAR";
                        break;
                    // Ação a ser executada caso o usuário clique em "Não"
                    case JOptionPane.NO_OPTION:
                        jTCpf.requestFocus();

                    // Ação a ser executada caso o usuário feche a caixa de diálogo sem escolher uma opção
                    default:
                        jTCpf.requestFocus();
                }

            }
        }
    }//GEN-LAST:event_jTCpfFocusLost

    private void jTCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCnpjFocusLost
        if (!new Validacao().validarCNPJ(jTCnpj.getText())) {
            JOptionPane.showMessageDialog(null, "CNPJ INVALIDO", "CNPJ INVALIDO", WIDTH);
            jTCnpj.requestFocus();
        }

    }//GEN-LAST:event_jTCnpjFocusLost

    private void jTNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomeKeyPressed
        String tam = jTNome.getText();

        if (jTNome.getText().isEmpty()) {
            jListCliente.setVisible(false);
        } else if (tam.length() > 2) {
            ListaPesquisa();
        }
    }//GEN-LAST:event_jTNomeKeyPressed

    private void jListClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClienteMouseClicked
        inserirCliente();
        jListCliente.setVisible(false);
    }//GEN-LAST:event_jListClienteMouseClicked

    private void jTDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDataNascimentoFocusGained
        try {
        MaskFormatter mask = new MaskFormatter("##/##/####");
        mask.install((JFormattedTextField) jTDataNascimento);
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jTDataNascimentoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvar;
    private javax.swing.JList<String> jListCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTBairroComercio;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTCep;
    private javax.swing.JTextField jTCnpj;
    private javax.swing.JTextField jTCpf;
    private javax.swing.JTextField jTDataNascimento;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNomeComercio;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTNumeroComercio;
    private javax.swing.JTextField jTRecado;
    private javax.swing.JTextField jTRg;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTRuaComercio;
    // End of variables declaration//GEN-END:variables

    private void criarCliente() {
        if (!validaCampos()) {
            JOptionPane.showMessageDialog(null, erros, "Campo Obrigatórios", WIDTH);

        } else {
            salvarCliente();

        }

    }

    private boolean validaCampos() {
        erros = new StringBuilder();
        if (jTNome.getText().trim().isEmpty()) {
            erros.append("Campo NOME Obrigatório \n");
        }
        if (jTCpf.getText().trim().isEmpty()) {
            erros.append("Campo CPF é Obrigatório \n");
        }
        if (jTRua.getText().trim().isEmpty()) {
            erros.append("Campo RUA é Obrigatório \n");
        }
        if (jTNumero.getText().trim().isEmpty()) {
            erros.append("Campo NÚMERO é Obrigatório \n");
        }
        if (jTBairro.getText().trim().isEmpty()) {
            erros.append("Campo BAIRRO é Obrigatório \n");
        }
        if (jTCelular.getText().trim().isEmpty()) {
            erros.append("Campo TELEFONE é Obrigatório \n");
        }

        if (erros.length() <= 0) {
            return true;
        } else {

            return false;
        }
    }

    private void salvarCliente() {
        Rm_Cliente novoCliente = new Rm_Cliente();

        //Dados pessoais
        novoCliente.setNome(jTNome.getText());
        novoCliente.setCpf(jTCpf.getText().replaceAll("[^0-9]", ""));
        novoCliente.setRg(jTRg.getText());
        novoCliente.setTelefone(jTCelular.getText());
        novoCliente.setTelefoneRecado(jTRecado.getText());
        novoCliente.setDataNascimento(jTDataNascimento.getText());
        novoCliente.setEmail(jTEmail.getText());
        //Endereco
        novoCliente.setRua(jTRua.getText());
        novoCliente.setBairro(jTBairro.getText());
        novoCliente.setNumero(jTNumero.getText());
        novoCliente.setCep(jTCep.getText());

        //dados comercio
        novoCliente.setNomeComercio(jTNomeComercio.getText());
        novoCliente.setCnpj(jTCnpj.getText());
        novoCliente.setRuaComercio(jTRuaComercio.getText());
        novoCliente.setNumeroComercio(jTNumeroComercio.getText());
        //cliente.setColaborador(colaborador);

        Repository.getInstance().cadastrarCliente(novoCliente);
        JOptionPane.showMessageDialog(null, "CLIENTE CADASTRADO!", "Sucesso", WIDTH);
        limpar();

    }

    private void atualizarCliente(Rm_Cliente cliente) {
        //Dados pessoais
        cliente.setNome(jTNome.getText());
        cliente.setCpf(jTCpf.getText().replaceAll("[^0-9]", ""));
        cliente.setRg(jTRg.getText());
        cliente.setTelefone(jTCelular.getText());
        cliente.setTelefoneRecado(jTRecado.getText());
        cliente.setDataNascimento(jTDataNascimento.getText());
        cliente.setEmail(jTEmail.getText());
        //Endereco
        cliente.setRua(jTRua.getText());
        cliente.setBairro(jTBairro.getText());
        cliente.setNumero(jTNumero.getText());
        cliente.setCep(jTCep.getText());

        //dados comercio
        cliente.setNomeComercio(jTNomeComercio.getText());
        cliente.setCnpj(jTCnpj.getText());
        cliente.setRuaComercio(jTRuaComercio.getText());
        cliente.setNumeroComercio(jTNumeroComercio.getText());
        //cliente.setColaborador(colaborador);

        Repository.getInstance().cadastrarCliente(cliente);
        JOptionPane.showMessageDialog(null, "DADOS ATUALIZADOS!", "Sucesso", WIDTH);
        operacao = "CRIAR";
        limpar();
    }

    private void limpar() {
        dispose();
        JInternalFrame cliente = new ClienteCadastro(colaborador);
        jDesktopPane.add(cliente);
        cliente.setVisible(true);

    }

    private void carregarFormulario(Rm_Cliente cliente) {
        jTNome.setText(cliente.getNome());
        jTCpf.setText(new Validacao().formatarCpf(cliente.getCpf()));
        jTRg.setText(cliente.getRg());
        jTCelular.setText(cliente.getTelefone());
        jTRecado.setText(cliente.getTelefoneRecado());
        jTDataNascimento.setText(cliente.getDataNascimento());
        jTEmail.setText(cliente.getEmail());

        //Endereco
        jTRua.setText(cliente.getRua());
        jTBairro.setText(cliente.getBairro());
        jTNumero.setText(cliente.getNumero());
        jTCep.setText(cliente.getCep());

        //dados comercio
        jTNomeComercio.setText(cliente.getNomeComercio());
        jTCnpj.setText(cliente.getCnpj());
        jTRuaComercio.setText(cliente.getRuaComercio());
        jTNumeroComercio.setText(cliente.getNumeroComercio());
        //cliente.setColaborador(colaborador);

    }

    private void ListaPesquisa() {
        modelo = new DefaultListModel();
        clienteList = Repository.getInstance().buscarClienteNome(jTNome.getText());
        modelo.removeAllElements();
        if ((clienteList != null) && (!clienteList.isEmpty())) {
            for (Rm_Cliente c : clienteList) {
                modelo.addElement(c.getNome());

            }

            jListCliente.setModel(modelo);
            jListCliente.setVisible(true);
        }

    }

    private void inserirCliente() {
        int linha = jListCliente.getSelectedIndex();
        for (Rm_Cliente c : clienteList) {
            if (c.getNome().equals(modelo.getElementAt(linha))) {
                cliente = c;
                carregarFormulario(cliente);
                operacao = "EDITAR";
            }
        }

    }

}
