/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.rm.veiw;

import br.rm.controle.ColaboradorRenderer;
import br.rm.controle.FormatacaoMoeda;
import br.rm.controle.Repository;
import br.rm.controle.StatusEmprestimo;
import br.rm.controle.StatusParcela;
import br.rm.modelo.Rm_Colaborador;
import br.rm.modelo.Rm_Emprestimo;
import br.rm.modelo.Rm_Parcela;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.xml.crypto.Data;

/**
 *
 * @author DEV
 */
public class Cobrancas extends javax.swing.JInternalFrame {

    private List<Rm_Colaborador> colaboradores;
    private Rm_Colaborador colaborador;
    private StringBuilder clienteAtrasado;
    private FormatacaoMoeda format;

    public Cobrancas() {
        initComponents();

        format = new FormatacaoMoeda();
        buscarTodosColaborador();
        comboBoxColaborador.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                colaborador = (Rm_Colaborador) comboBoxColaborador.getSelectedItem();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxColaborador = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jListar = new javax.swing.JButton();
        jSalvarPdf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAClientesACobrar = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Cobranças");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comboBoxColaborador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxColaborador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Selecione o colaborador ");

        jListar.setBackground(new java.awt.Color(51, 51, 51));
        jListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jListar.setForeground(new java.awt.Color(255, 255, 255));
        jListar.setText("Listar");
        jListar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListar.setFocusPainted(false);
        jListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jListarMouseExited(evt);
            }
        });
        jListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarActionPerformed(evt);
            }
        });

        jSalvarPdf.setBackground(new java.awt.Color(51, 51, 51));
        jSalvarPdf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSalvarPdf.setForeground(new java.awt.Color(255, 255, 255));
        jSalvarPdf.setText("Salvar PDF");
        jSalvarPdf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSalvarPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSalvarPdf.setFocusPainted(false);
        jSalvarPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSalvarPdfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSalvarPdfMouseExited(evt);
            }
        });
        jSalvarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarPdfActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lista de Cobranças", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jTAClientesACobrar.setEditable(false);
        jTAClientesACobrar.setColumns(20);
        jTAClientesACobrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTAClientesACobrar.setRows(5);
        jTAClientesACobrar.setBorder(null);
        jScrollPane3.setViewportView(jTAClientesACobrar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jListar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jSalvarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalvarPdf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jListar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListarMouseEntered
        jListar.setBackground(new Color(153, 153, 0));
        jListar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jListarMouseEntered

    private void jListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListarMouseExited
        jListar.setBackground(new Color(51, 51, 51));
        jListar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jListarMouseExited

    private void jListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarActionPerformed
        buscarCobrancas();
    }//GEN-LAST:event_jListarActionPerformed

    private void jSalvarPdfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarPdfMouseEntered
        jSalvarPdf.setBackground(new Color(153, 153, 0));
        jSalvarPdf.setForeground(Color.WHITE);
    }//GEN-LAST:event_jSalvarPdfMouseEntered

    private void jSalvarPdfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarPdfMouseExited
        jSalvarPdf.setBackground(new Color(51, 51, 51));
        jSalvarPdf.setForeground(Color.WHITE);
    }//GEN-LAST:event_jSalvarPdfMouseExited

    private void jSalvarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarPdfActionPerformed
        if (clienteAtrasado.length() > 0) {
            String caminho = obterCaminho();
            salvarPDF(clienteAtrasado, caminho);
        } else {
            JOptionPane.showMessageDialog(null, "NENHUMA COBRANÇA ENCONTRADA", "ALERTA", WIDTH);
        }
    }//GEN-LAST:event_jSalvarPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Rm_Colaborador> comboBoxColaborador;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalvarPdf;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAClientesACobrar;
    // End of variables declaration//GEN-END:variables

    private void buscarTodosColaborador() {
        colaboradores = Repository.getInstance().buscarTodosColaborador();
        DefaultComboBoxModel<Rm_Colaborador> tipoComboBox = new DefaultComboBoxModel<>();

        for (Rm_Colaborador c : colaboradores) {
            tipoComboBox.addElement(c);
        }

        comboBoxColaborador.setModel(tipoComboBox);
        comboBoxColaborador.setRenderer(new ColaboradorRenderer());

    }

    private void buscarCobrancas() {
        colaborador = (Rm_Colaborador) comboBoxColaborador.getSelectedItem();
        List<Rm_Emprestimo> emprestimosACobrar = new ArrayList<>();

        if (verificaEmprestimoAberto()) {
            for (Rm_Emprestimo emprestimo : colaborador.getEmprestimos()) {
                if (emprestimo.getStatus().equals(StatusEmprestimo.ABERTO)) {
                    boolean hasOpenParcel = false;

                    for (Rm_Parcela parcela : emprestimo.getParcela()) {
                        if (parcela.getStatus().equals(StatusParcela.ATRASADA)) {
                            emprestimosACobrar.add(emprestimo);
                            break; // Adicionou o empréstimo, não precisa verificar outras parcelas
                        } else if (parcela.getDataVencimento().equals(new Date())) {
                            hasOpenParcel = true;
                        }
                    }

                    if (hasOpenParcel) {
                        emprestimosACobrar.add(emprestimo);
                    }
                }
            }

            // Atualizar as parcelas apenas para as que devem ser mantidas
            for (Rm_Emprestimo emprestimo : emprestimosACobrar) {
                List<Rm_Parcela> parcelasMantidas = new ArrayList<>();
                for (Rm_Parcela parcela : emprestimo.getParcela()) {
                    if (parcela.getStatus().equals(StatusParcela.ATRASADA)
                            || (parcela.getStatus().equals(StatusParcela.ABERTA) && parcela.getDataFormatada().equals(getData()))) {
                        parcelasMantidas.add(parcela);
                    }
                }
                emprestimo.setParcela(parcelasMantidas);
            }

            listar(emprestimosACobrar);
        } else {
            JOptionPane.showMessageDialog(null, "NENHUMA COBRANÇA ENCONTRADA", "ALERTA", WIDTH);
            clienteAtrasado = new StringBuilder();
            jTAClientesACobrar.setText("");
        }
    }

    private void listar(List<Rm_Emprestimo> emprestimos) {
        clienteAtrasado = new StringBuilder();
        for (Rm_Emprestimo emprestimo : emprestimos) {
            //clienteAtrasado.append("Tempo de atraso: ").append(cliente.getNome()).append("\n");
            clienteAtrasado.append("Nome: ").append(emprestimo.getCliente().getNome()).append("\n");
            clienteAtrasado.append("Telefone: ").append(emprestimo.getCliente().getTelefone()).append("\n");
            clienteAtrasado.append("Rua: ").append(emprestimo.getCliente().getRua()).append("  Nº: ").append(emprestimo.getCliente().getNumero()).append("\n");
            clienteAtrasado.append("Bairro: ").append(emprestimo.getCliente().getBairro()).append("\n");
            clienteAtrasado.append("EMPRÉSTIMO: ").append(format.formatarMoeda(emprestimo.getValorEmprestimo())).append("   JUROS: ").append(format.formatarPercentual(emprestimo.getTaxaJuros())).append("   VALOR Á PAGAR: ").append(format.formatarMoeda(emprestimo.getValorTotalPagar())).append("\n");
            clienteAtrasado.append("Cobrador Responsavel: ").append(emprestimo.getColaborador().getNome()).append("\n\n");
            clienteAtrasado.append("                                                         ===== PARCELAS ===== ").append("\n\n");
            clienteAtrasado.append("   =NÚMERO=         =VENCIMENTO=        =VALOR=         =JUROS DIÁRIO=    =STATUS=").append("\n");

            //ordenar a lista emprestimos.getParcela()
            emprestimo.getParcela().sort((parcela1, parcela2) -> Integer.compare(parcela1.getNumeroParcela(), parcela2.getNumeroParcela()));
            for (Rm_Parcela parcela : emprestimo.getParcela()) {
                clienteAtrasado.append("            ").append(parcela.getNumeroParcela()).append("                       ").append(parcela.getDataFormatada()).append("                    ").append(format.formatarMoeda(parcela.getValor())).append("              ").append(format.formatarMoeda(parcela.getValorJurosDiario())).append("                       ").append(parcela.getStatus()).append("  \n");
            }
            clienteAtrasado.append("_______________________________________________________________________________________\n");

        }
        jTAClientesACobrar.setText(clienteAtrasado.toString());

    }

    private boolean verificaEmprestimoAberto() {

        for (Rm_Emprestimo emprestimo : colaborador.getEmprestimos()) {
            if (emprestimo.getStatus().equals(StatusEmprestimo.ABERTO)) {
                return true;

            }
        }
        return false;
    }

// ...
    private void salvarPDF(StringBuilder conteudo, String caminhoArquivo) {
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(caminhoArquivo));
            document.open();

            // Crie uma instância da fonte Helvetica-Bold
            Font fontBold = new Font(Font.TIMES_ROMAN, 12, Font.BOLD);

            Paragraph paragraph = new Paragraph(conteudo.toString(), fontBold);
            document.add(paragraph);

            document.close();

            System.out.println("PDF salvo em: " + caminhoArquivo);

            // Abre o arquivo PDF com o aplicativo padrão
            File pdfFile = new File(caminhoArquivo);
            if (pdfFile.exists()) {
                Desktop.getDesktop().open(pdfFile);
            }
        } catch (DocumentException | IOException e) {
            e.printStackTrace();
        }
    }

    private String obterCaminho() {
        // Obter o caminho da pasta "Documentos" do sistema
        String documentosPath = System.getProperty("user.home") + File.separator + "Documents";

        // Criar uma nova pasta dentro da pasta "Documentos"
        String novaPastaPath = documentosPath + File.separator + "Cobranças RM Empréstimos";

        File novaPasta = new File(novaPastaPath);
        if (novaPasta.exists()) {
            return novaPastaPath + File.separator + colaborador.getNome() + ".pdf";
        } else {
            novaPasta.mkdir();
            return novaPastaPath + File.separator + colaborador.getNome() + ".pdf";
        }

    }

    private String getData() {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        return format.format(new Date());
    }
}
