/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.rm.veiw;

import br.rm.controle.ColaboradorRenderer;
import br.rm.controle.Repository;
import br.rm.modelo.Rm_Colaborador;
import br.rm.modelo.Rm_PermissaoUsuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DEV
 */
public class ConfiguracoesPermissao extends javax.swing.JInternalFrame {

    private List<Rm_Colaborador> colaboradores;
    private Rm_Colaborador colaborador;

    public ConfiguracoesPermissao() {
        initComponents();
        buscarTodosColaborador();
          setFrameIcon(new ImageIcon(getClass().getResource("/icons/config.png")));
        comboBoxColaborador.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                carregarPermissoes();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxColaborador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cadastros = new javax.swing.JCheckBox();
        criarEmprestimo = new javax.swing.JCheckBox();
        relatorio = new javax.swing.JCheckBox();
        ganho = new javax.swing.JCheckBox();
        configuracao = new javax.swing.JCheckBox();
        baixarEmprestimo = new javax.swing.JCheckBox();
        recalculoEmprestimo = new javax.swing.JCheckBox();
        jSalvar = new javax.swing.JButton();
        administrador = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Permissões");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comboBoxColaborador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxColaborador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecione o colaborador ");

        cadastros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastros.setText("Cadastros");

        criarEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        criarEmprestimo.setText("Criar empréstimos");

        relatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        relatorio.setText("Relatórios");

        ganho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ganho.setText("Ganhos");

        configuracao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        configuracao.setText("Configurações");

        baixarEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        baixarEmprestimo.setText("Baixar empréstimos");

        recalculoEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recalculoEmprestimo.setText("Recálcular empréstimos");

        jSalvar.setBackground(new java.awt.Color(51, 51, 51));
        jSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jSalvar.setText("Salvar");
        jSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSalvar.setFocusPainted(false);
        jSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSalvarMouseExited(evt);
            }
        });
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        administrador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        administrador.setText("Administrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criarEmprestimo)
                            .addComponent(relatorio)
                            .addComponent(ganho)
                            .addComponent(cadastros))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(configuracao)
                            .addComponent(baixarEmprestimo)
                            .addComponent(recalculoEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(comboBoxColaborador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(comboBoxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastros)
                    .addComponent(configuracao))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(baixarEmprestimo)
                        .addGap(20, 20, 20)
                        .addComponent(recalculoEmprestimo)
                        .addGap(20, 20, 20)
                        .addComponent(administrador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(criarEmprestimo)
                        .addGap(20, 20, 20)
                        .addComponent(relatorio)
                        .addGap(20, 20, 20)
                        .addComponent(ganho)))
                .addGap(15, 15, 15)
                .addComponent(jSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarMouseEntered
        jSalvar.setBackground(new Color(153, 153, 0));
        jSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jSalvarMouseEntered

    private void jSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarMouseExited
        jSalvar.setBackground(new Color(51, 51, 51));
        jSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jSalvarMouseExited

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_jSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox administrador;
    private javax.swing.JCheckBox baixarEmprestimo;
    private javax.swing.JCheckBox cadastros;
    private javax.swing.JComboBox<Rm_Colaborador> comboBoxColaborador;
    private javax.swing.JCheckBox configuracao;
    private javax.swing.JCheckBox criarEmprestimo;
    private javax.swing.JCheckBox ganho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalvar;
    private javax.swing.JCheckBox recalculoEmprestimo;
    private javax.swing.JCheckBox relatorio;
    // End of variables declaration//GEN-END:variables

    private void buscarTodosColaborador() {
        colaboradores = Repository.getInstance().buscarTodosColaborador();
        DefaultComboBoxModel<Rm_Colaborador> tipoComboBox = new DefaultComboBoxModel<>();

        for (Rm_Colaborador c: colaboradores) {
            tipoComboBox.addElement(c);
        }

        comboBoxColaborador.setModel(tipoComboBox);
        comboBoxColaborador.setRenderer(new ColaboradorRenderer());
        carregarPermissoes();
    }

    private void carregarPermissoes() {
        colaborador = (Rm_Colaborador) comboBoxColaborador.getSelectedItem();
        if (colaborador.getPermissaoUsuario() != null) {
            cadastros.setSelected(colaborador.getPermissaoUsuario().isCadastro());
            criarEmprestimo.setSelected(colaborador.getPermissaoUsuario().isNovoEmprestimo());
            relatorio.setSelected(colaborador.getPermissaoUsuario().isRelatorio());
            ganho.setSelected(colaborador.getPermissaoUsuario().isGanhos());
            configuracao.setSelected(colaborador.getPermissaoUsuario().isConfiguracoes());
            baixarEmprestimo.setSelected(colaborador.getPermissaoUsuario().isBaixarEmprestimo());
            recalculoEmprestimo.setSelected(colaborador.getPermissaoUsuario().isRecalculoEmprestimo());
        }else{
                 cadastros.setSelected(false);
            criarEmprestimo.setSelected(false);
            relatorio.setSelected(false);
            ganho.setSelected(false);
            configuracao.setSelected(false);
            baixarEmprestimo.setSelected(false);
            recalculoEmprestimo.setSelected(false);
        
        }
            
    }

    private void salvar() {
        if (colaborador.getPermissaoUsuario() == null) {
            criarPermissao();
        } else {
            atualizarPermissao();
        }

    }

    private void criarPermissao() {
        Rm_PermissaoUsuario permissaoUsuario = new Rm_PermissaoUsuario();

        permissaoUsuario.setCadastro(cadastros.isSelected());
        permissaoUsuario.setNovoEmprestimo(criarEmprestimo.isSelected());
        permissaoUsuario.setRelatorio(relatorio.isSelected());
        permissaoUsuario.setGanhos(ganho.isSelected());
        permissaoUsuario.setConfiguracoes(configuracao.isSelected());
        permissaoUsuario.setRecalculoEmprestimo(recalculoEmprestimo.isSelected());
        permissaoUsuario.setBaixarEmprestimo(baixarEmprestimo.isSelected());
        permissaoUsuario.setColaborador(colaborador);
        
        Repository.getInstance().criarEatualizarPermissoes(permissaoUsuario);
        JOptionPane.showMessageDialog(null, "Permissões atualizadas com sucesso", "Sucesso", WIDTH);

    }

    private void atualizarPermissao() {

        colaborador.getPermissaoUsuario().setGanhos(cadastros.isSelected());
        colaborador.getPermissaoUsuario().setNovoEmprestimo(criarEmprestimo.isSelected());
        colaborador.getPermissaoUsuario().setRelatorio(relatorio.isSelected());
        colaborador.getPermissaoUsuario().setGanhos(ganho.isSelected());
        colaborador.getPermissaoUsuario().setConfiguracoes(configuracao.isSelected());
        colaborador.getPermissaoUsuario().setBaixarEmprestimo(baixarEmprestimo.isSelected());
        colaborador.getPermissaoUsuario().setRecalculoEmprestimo(recalculoEmprestimo.isSelected());

        Repository.getInstance().criarEatualizarPermissoes(colaborador.getPermissaoUsuario());
        JOptionPane.showMessageDialog(null, "Permissões atualizadas com sucesso", "Sucesso", WIDTH);
    }
}
