/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.rm.veiw;

import br.rm.controle.Repository;
import br.rm.modelo.Rm_Colaborador;
import br.rm.modelo.Rm_Parcela;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Jean
 */
public class Inicio extends javax.swing.JFrame {

    private Rm_Colaborador colaborador;
    private String modoMenu;
    private List<Rm_Parcela> parcelas;

    public Inicio() {

        initComponents();

        jLPrincipal.setBackground(new Color(51, 51, 51));
        setExtendedState(MAXIMIZED_BOTH);
        this.modoMenu = "INICIAL";
        iniciarMenu(modoMenu);
        setIcones();
        setVisible(true);
        atualizaParcelaAtrazo();
    }

    public Inicio(Rm_Colaborador colaborador) {
        this.colaborador = colaborador;
        initComponents();

        jLPrincipal.setBackground(new Color(51, 51, 51));
        setExtendedState(MAXIMIZED_BOTH);
        iniciarMenu(this.modoMenu = "INICIAL");
        setIcones();
        setVisible(true);
        setTitle("RM Empréstimos - " + this.colaborador.getNome());
        atualizaParcelaAtrazo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jBCliente = new javax.swing.JButton();
        jBColaborador = new javax.swing.JButton();
        jBEmprestimo = new javax.swing.JButton();
        MenuCadastraColaborador = new javax.swing.JLabel();
        MenuGanhos = new javax.swing.JLabel();
        MenuCobranca = new javax.swing.JLabel();
        MenuNovoEmprestimo = new javax.swing.JLabel();
        MenuBuscaEmprestimo = new javax.swing.JLabel();
        baixaEmprestimo = new javax.swing.JLabel();
        jBRelatorio = new javax.swing.JButton();
        MenuRelatorio = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jLPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMenu.setForeground(new java.awt.Color(51, 51, 51));
        jPanelMenu.setAutoscrolls(true);

        jBCliente.setBackground(new java.awt.Color(51, 51, 51));
        jBCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBCliente.setForeground(new java.awt.Color(255, 255, 255));
        jBCliente.setText("Cliente");
        jBCliente.setBorderPainted(false);
        jBCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBCliente.setFocusPainted(false);
        jBCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBCliente.setIconTextGap(5);
        jBCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBClienteMouseExited(evt);
            }
        });
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });

        jBColaborador.setBackground(new java.awt.Color(51, 51, 51));
        jBColaborador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBColaborador.setForeground(new java.awt.Color(255, 255, 255));
        jBColaborador.setText("Colaborador");
        jBColaborador.setBorderPainted(false);
        jBColaborador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBColaborador.setFocusPainted(false);
        jBColaborador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBColaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBColaboradorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBColaboradorMouseExited(evt);
            }
        });
        jBColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBColaboradorActionPerformed(evt);
            }
        });

        jBEmprestimo.setBackground(new java.awt.Color(51, 51, 51));
        jBEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jBEmprestimo.setText("Emprestimo");
        jBEmprestimo.setBorderPainted(false);
        jBEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBEmprestimo.setFocusPainted(false);
        jBEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEmprestimoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEmprestimoMouseExited(evt);
            }
        });
        jBEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmprestimoActionPerformed(evt);
            }
        });

        MenuCadastraColaborador.setBackground(new java.awt.Color(51, 51, 51));
        MenuCadastraColaborador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuCadastraColaborador.setForeground(new java.awt.Color(255, 255, 255));
        MenuCadastraColaborador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuCadastraColaborador.setText("Cadastrar");
        MenuCadastraColaborador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuCadastraColaborador.setOpaque(true);
        MenuCadastraColaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCadastraColaboradorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuCadastraColaboradorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuCadastraColaboradorMouseExited(evt);
            }
        });

        MenuGanhos.setBackground(new java.awt.Color(51, 51, 51));
        MenuGanhos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuGanhos.setForeground(new java.awt.Color(255, 255, 255));
        MenuGanhos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuGanhos.setText("Ganhos");
        MenuGanhos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuGanhos.setOpaque(true);
        MenuGanhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuGanhosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuGanhosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuGanhosMouseExited(evt);
            }
        });

        MenuCobranca.setBackground(new java.awt.Color(51, 51, 51));
        MenuCobranca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuCobranca.setForeground(new java.awt.Color(255, 255, 255));
        MenuCobranca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuCobranca.setText("Cobranças");
        MenuCobranca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuCobranca.setOpaque(true);
        MenuCobranca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuCobrancaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuCobrancaMouseExited(evt);
            }
        });

        MenuNovoEmprestimo.setBackground(new java.awt.Color(51, 51, 51));
        MenuNovoEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuNovoEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        MenuNovoEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuNovoEmprestimo.setText("Novo");
        MenuNovoEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuNovoEmprestimo.setOpaque(true);
        MenuNovoEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNovoEmprestimoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuNovoEmprestimoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuNovoEmprestimoMouseExited(evt);
            }
        });

        MenuBuscaEmprestimo.setBackground(new java.awt.Color(51, 51, 51));
        MenuBuscaEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuBuscaEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        MenuBuscaEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuBuscaEmprestimo.setText("Buscar");
        MenuBuscaEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBuscaEmprestimo.setOpaque(true);
        MenuBuscaEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuBuscaEmprestimoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuBuscaEmprestimoMouseExited(evt);
            }
        });

        baixaEmprestimo.setBackground(new java.awt.Color(51, 51, 51));
        baixaEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        baixaEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        baixaEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baixaEmprestimo.setText("Baixar");
        baixaEmprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        baixaEmprestimo.setOpaque(true);
        baixaEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baixaEmprestimoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                baixaEmprestimoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                baixaEmprestimoMouseExited(evt);
            }
        });

        jBRelatorio.setBackground(new java.awt.Color(51, 51, 51));
        jBRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        jBRelatorio.setText("Relátorios");
        jBRelatorio.setBorderPainted(false);
        jBRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBRelatorio.setFocusPainted(false);
        jBRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBRelatorioMouseExited(evt);
            }
        });
        jBRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioActionPerformed(evt);
            }
        });

        MenuRelatorio.setBackground(new java.awt.Color(51, 51, 51));
        MenuRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        MenuRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuRelatorio.setText("Baixar");
        MenuRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuRelatorio.setOpaque(true);
        MenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuRelatorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuRelatorioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBColaborador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jBEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MenuCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(MenuGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MenuCadastraColaborador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(1, 1, 1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baixaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MenuBuscaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MenuNovoEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MenuRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jBRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(MenuCadastraColaborador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuGanhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuCobranca)
                .addGap(20, 20, 20)
                .addComponent(jBEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(MenuNovoEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuBuscaEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baixaEmprestimo)
                .addGap(20, 20, 20)
                .addComponent(jBRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(MenuRelatorio)
                .addContainerGap())
        );

        jDesktopPane.setBackground(new java.awt.Color(51, 51, 51));
        jDesktopPane.setForeground(new java.awt.Color(51, 51, 51));
        jDesktopPane.setToolTipText("");

        jLPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jLPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jLPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/rm/icons/RM.png"))); // NOI18N
        jLPrincipal.setOpaque(true);

        jDesktopPane.setLayer(jLPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 949, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                .addComponent(jLPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClienteMouseEntered
        jBCliente.setBackground(new Color(153, 153, 0));
        jBCliente.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBClienteMouseEntered

    private void jBClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClienteMouseExited
        jBCliente.setBackground(new Color(51, 51, 51));
        jBCliente.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBClienteMouseExited

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        fecharAbas();
        iniciarMenu("INICIAL");
        JInternalFrame cliente = new ClienteCadastro(colaborador);
        jDesktopPane.add(cliente);
        cliente.setVisible(true);
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jBColaboradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBColaboradorMouseEntered
        jBColaborador.setBackground(new Color(153, 153, 0));
        jBColaborador.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBColaboradorMouseEntered

    private void jBColaboradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBColaboradorMouseExited
        jBColaborador.setBackground(new Color(51, 51, 51));
        jBColaborador.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBColaboradorMouseExited

    private void jBColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBColaboradorActionPerformed

        //MenuCadastraColaborador.setText("Cadastrar");
        //MenuCobranca.setText("Cobranças");
        // MenuGanhos.setText("Ganhos");
        iniciarMenu("COLABORADOR");
        // MenuCadastraColaborador.setVisible(true);
        //MenuCobranca.setVisible(true);
        //MenuGanhos.setVisible(true);
    }//GEN-LAST:event_jBColaboradorActionPerformed

    private void jBEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEmprestimoMouseEntered
        jBEmprestimo.setBackground(new Color(153, 153, 0));
        jBEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBEmprestimoMouseEntered

    private void jBEmprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEmprestimoMouseExited
        jBEmprestimo.setBackground(new Color(51, 51, 51));
        jBEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBEmprestimoMouseExited

    private void jBEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmprestimoActionPerformed
        iniciarMenu("EMPRESTIMO");
    }//GEN-LAST:event_jBEmprestimoActionPerformed

    private void MenuCadastraColaboradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastraColaboradorMouseEntered
        MenuCadastraColaborador.setBackground(new Color(153, 153, 0));
        MenuCadastraColaborador.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuCadastraColaboradorMouseEntered

    private void MenuGanhosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuGanhosMouseExited
        MenuGanhos.setBackground(new Color(51, 51, 51));
        MenuGanhos.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuGanhosMouseExited

    private void MenuCadastraColaboradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastraColaboradorMouseExited
        MenuCadastraColaborador.setBackground(new Color(51, 51, 51));
        MenuCadastraColaborador.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuCadastraColaboradorMouseExited

    private void MenuGanhosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuGanhosMouseEntered
        MenuGanhos.setBackground(new Color(153, 153, 0));
        MenuGanhos.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuGanhosMouseEntered

    private void MenuCobrancaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCobrancaMouseEntered
        MenuCobranca.setBackground(new Color(153, 153, 0));
        MenuCobranca.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuCobrancaMouseEntered

    private void MenuCobrancaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCobrancaMouseExited
        MenuCobranca.setBackground(new Color(51, 51, 51));
        MenuCobranca.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuCobrancaMouseExited

    private void MenuCadastraColaboradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastraColaboradorMouseClicked
        fecharAbas();
        JInternalFrame colaborador = new ColaboradorCadastro();
        jDesktopPane.add(colaborador);
        colaborador.setVisible(true);
    }//GEN-LAST:event_MenuCadastraColaboradorMouseClicked

    private void MenuNovoEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoEmprestimoMouseClicked
        fecharAbas();
        JInternalFrame novoEmprestimo = new NovoEmprestimo();
        jDesktopPane.add(novoEmprestimo);
        novoEmprestimo.setVisible(true);
    }//GEN-LAST:event_MenuNovoEmprestimoMouseClicked

    private void MenuNovoEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoEmprestimoMouseEntered
        MenuNovoEmprestimo.setBackground(new Color(153, 153, 0));
        MenuNovoEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuNovoEmprestimoMouseEntered

    private void MenuNovoEmprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNovoEmprestimoMouseExited
        MenuNovoEmprestimo.setBackground(new Color(51, 51, 51));
        MenuNovoEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuNovoEmprestimoMouseExited

    private void MenuBuscaEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBuscaEmprestimoMouseEntered
        MenuBuscaEmprestimo.setBackground(new Color(153, 153, 0));
        MenuBuscaEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuBuscaEmprestimoMouseEntered

    private void MenuBuscaEmprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBuscaEmprestimoMouseExited
        MenuBuscaEmprestimo.setBackground(new Color(51, 51, 51));
        MenuBuscaEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_MenuBuscaEmprestimoMouseExited

    private void baixaEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baixaEmprestimoMouseEntered
        baixaEmprestimo.setBackground(new Color(153, 153, 0));
        baixaEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_baixaEmprestimoMouseEntered

    private void baixaEmprestimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baixaEmprestimoMouseExited
        baixaEmprestimo.setBackground(new Color(51, 51, 51));
        baixaEmprestimo.setForeground(Color.WHITE);
    }//GEN-LAST:event_baixaEmprestimoMouseExited

    private void jBRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRelatorioMouseEntered
        jBRelatorio.setBackground(new Color(153, 153, 0));
        jBRelatorio.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBRelatorioMouseEntered

    private void jBRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRelatorioMouseExited
        jBRelatorio.setBackground(new Color(51, 51, 51));
        jBRelatorio.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBRelatorioMouseExited

    private void jBRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioActionPerformed
        iniciarMenu("RELATORIO");
    }//GEN-LAST:event_jBRelatorioActionPerformed

    private void baixaEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baixaEmprestimoMouseClicked
        fecharAbas();
        JInternalFrame baixarParcela = new BaixarParcelaEmprestimo();
        jDesktopPane.add(baixarParcela);
        baixarParcela.setVisible(true);
    }//GEN-LAST:event_baixaEmprestimoMouseClicked

    private void MenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRelatorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatorioMouseClicked

    private void MenuRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRelatorioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatorioMouseEntered

    private void MenuRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRelatorioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatorioMouseExited

    private void MenuGanhosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuGanhosMouseClicked
         fecharAbas();
        JInternalFrame ganhosColaborador = new GanhosColaborador();
        jDesktopPane.add(ganhosColaborador);
       ganhosColaborador.setVisible(true);
    }//GEN-LAST:event_MenuGanhosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuBuscaEmprestimo;
    private javax.swing.JLabel MenuCadastraColaborador;
    private javax.swing.JLabel MenuCobranca;
    private javax.swing.JLabel MenuGanhos;
    private javax.swing.JLabel MenuNovoEmprestimo;
    private javax.swing.JLabel MenuRelatorio;
    private javax.swing.JLabel baixaEmprestimo;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBColaborador;
    private javax.swing.JButton jBEmprestimo;
    private javax.swing.JButton jBRelatorio;
    public static javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLPrincipal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables

    public static void adicionarInternalframe(JInternalFrame frame) {
        jDesktopPane.add(frame);
        frame.setVisible(true);
    }

    private void fecharAbas() {
        for (JInternalFrame frame : jDesktopPane.getAllFrames()) {
            frame.dispose(); // Fechar cada JInternalFrame
        }
    }

    private void setIcones() {

        jBCliente.setIcon(new ImageIcon(getClass().getResource("/icons/usuario.png")));
        jBColaborador.setIcon(new ImageIcon(getClass().getResource("/icons/colaborador.png")));
        jBEmprestimo.setIcon(new ImageIcon(getClass().getResource("/icons/sack-dollar.png")));
        MenuGanhos.setIcon(new ImageIcon(getClass().getResource("/icons/coins.png")));
        MenuCadastraColaborador.setIcon(new ImageIcon(getClass().getResource("/icons/colaborador.png")));
        MenuCobranca.setIcon(new ImageIcon(getClass().getResource("/icons/bank.png")));
        MenuNovoEmprestimo.setIcon(new ImageIcon(getClass().getResource("/icons/add-document.png")));
        MenuBuscaEmprestimo.setIcon(new ImageIcon(getClass().getResource("/icons/search-alt.png")));
        baixaEmprestimo.setIcon(new ImageIcon(getClass().getResource("/icons/stats.png")));
        jBRelatorio.setIcon(new ImageIcon(getClass().getResource("/icons/report.png")));
        MenuRelatorio.setIcon(new ImageIcon(getClass().getResource("/icons/report.png")));
    }

    private void iniciarMenu(String modo) {
        this.modoMenu = modo;
        jPanelMenu.setBackground(new Color(51, 51, 51));
        jPanelMenu.setForeground(new Color(51, 51, 51));

        switch (modoMenu) {
            case "COLABORADOR":
                //ATIVA COLABORADOR
               MenuGanhos.setVisible(true);
                MenuCobranca.setVisible(true);
                MenuCadastraColaborador.setVisible(true);

                //DESATIVA OUTROS MENuS
               
                MenuBuscaEmprestimo.setVisible(false);
                baixaEmprestimo.setVisible(false);
                MenuNovoEmprestimo.setVisible(false);
               //destaviva menu relatorio
               MenuRelatorio.setVisible(false); 
                
                break;
            case "EMPRESTIMO":
                //ativa menu emprestimo
                MenuBuscaEmprestimo.setVisible(true);
                baixaEmprestimo.setVisible(true);
                MenuNovoEmprestimo.setVisible(true);
                //desativa outros menus
               
                MenuCobranca.setVisible(false);
                MenuRelatorio.setVisible(false); 
                MenuCadastraColaborador.setVisible(false);
                MenuGanhos.setVisible(false);

                break;
            case "INICIAL":
                //Desativa Menu Colaborador
                MenuCadastraColaborador.setVisible(false);
                MenuCobranca.setVisible(false);
                MenuGanhos.setVisible(false);
                //Desatativa Menu Emprestimos
                MenuBuscaEmprestimo.setVisible(false);
                baixaEmprestimo.setVisible(false);
                MenuNovoEmprestimo.setVisible(false);
                //desativa menu Relatorio
                 MenuRelatorio.setVisible(false); 
               
                

               
                break;
            case "RELATORIO":
                //ativa menu Relatorio
               MenuRelatorio.setVisible(true); 
               

                //desativa outros menus
                //Desativa Menu Colaborador
                MenuCadastraColaborador.setVisible(false);
                MenuCobranca.setVisible(false);
                MenuGanhos.setVisible(false);
                //Desatativa Menu Emprestimos
                MenuBuscaEmprestimo.setVisible(false);
                baixaEmprestimo.setVisible(false);
                MenuNovoEmprestimo.setVisible(false);
                break;
            default:
                //Desativa Menu Colaborador
                MenuCadastraColaborador.setVisible(false);
                MenuCobranca.setVisible(false);
                MenuGanhos.setVisible(false);
                //Desatativa Menu Emprestimos
                MenuBuscaEmprestimo.setVisible(false);
                baixaEmprestimo.setVisible(false);
                MenuNovoEmprestimo.setVisible(false);
                //desativa menu Relatorio
                MenuGanhos.setVisible(false);
                 MenuRelatorio.setVisible(false); 
              

                break;
        }
    }

    private void atualizaParcelaAtrazo() {
        parcelas = Repository.getInstance().buscarParcelasAtrazada();
        calcularMultaDiaria();

    }

    public void calcularMultaDiaria() {

        LocalDate dataAtual = LocalDate.now();
        List<Rm_Parcela> novaParcelas = new ArrayList<>();
        for (Rm_Parcela parcela : parcelas) {
            Date dataVencimento = parcela.getDataVencimento();
            LocalDate localDateVencimento = dataVencimento.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (localDateVencimento.isBefore(dataAtual)) {
                int diasAtraso = dataAtual.getDayOfMonth() - localDateVencimento.getDayOfMonth();

                parcela.setValorJurosDiario(diasAtraso * parcela.getTaxaJurosDiaria());
                parcela.setStatus("ATRASADA");
                novaParcelas.add(parcela);
            }
        }
        if (!novaParcelas.isEmpty()) {
            Repository.getInstance().atualizarParcela(novaParcelas);
        }

    }
}
