/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.rm.veiw;

import br.rm.controle.JDecimalTextField;
import br.rm.controle.ParcelasUtil;
import br.rm.controle.Repository;
import br.rm.modelo.Rm_Cliente;
import br.rm.modelo.Rm_Colaborador;
import br.rm.modelo.Rm_Emprestimo;
import br.rm.modelo.Rm_Parcela;
import br.rm.tabela.JBeanTable;
import br.rm.tabela.JBeanTableColumn;
import br.rm.tabela.JDecimalTableCellEditor;
import br.rm.tabela.JDecimalTableCellRenderer;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.JTextField;

/**
 *
 * @author Jayne
 */
public class NovoEmprestimo extends javax.swing.JInternalFrame {

    List<Rm_Cliente> clienteList;
    private Rm_Cliente cliente;
    DefaultListModel modelo;
    List<Rm_Colaborador> colaboradorList;
    private Rm_Colaborador colaborador;
    private JBeanTable jBTParcelas;
    private StringBuilder erros;
    private List<Rm_Parcela> parcelas;

    public NovoEmprestimo() {
        initComponents();
        criarTabela();
        jListCliente.setVisible(false);
        jListCobrador.setVisible(false);
        modelo = new DefaultListModel();
        jListCliente.setModel(modelo);
        jTdataLacamento.setDate(new Date());
        jTdataLacamento.setForeground(Color.WHITE);
        jCheckDiario.setSelected(true);
        setFrameIcon(new ImageIcon(getClass().getResource("/icons/add-document.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupVencimneto = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTCliente = new br.rm.controle.JTextFieldHint(new JTextField(), "Cliente");
        ;
        jListCliente = new javax.swing.JList<>();
        jTComissaoColaborador = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jLabel2 = new javax.swing.JLabel();
        jTValorEmprestar = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jLabel1 = new javax.swing.JLabel();
        jTPagamentoTotal = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jLabel3 = new javax.swing.JLabel();
        jTLucro = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jLabel5 = new javax.swing.JLabel();
        jTQtdParcela = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jLabel6 = new javax.swing.JLabel();
        jTdataLacamento = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTjuros = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jLabel10 = new javax.swing.JLabel();
        jTCobrador = new br.rm.controle.JTextFieldHint(new JTextField(), "Cobrador");
        ;
        jListCobrador = new javax.swing.JList<>();
        jCheckDiario = new javax.swing.JCheckBox();
        jCheckSemanal = new javax.swing.JCheckBox();
        jCheckQuinzenal = new javax.swing.JCheckBox();
        jCheckMensal = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTvalorJurosDiario = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jTValorParcela = new JDecimalTextField(2, JDecimalTextField.PRECISAO_DOUBLE);
        jBGerarParcela = new javax.swing.JButton();
        tipoSegundaSexta = new javax.swing.JCheckBox();
        tipoSegundaSabado = new javax.swing.JCheckBox();
        tipoSegundaSegunda = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneParcelas = new javax.swing.JScrollPane();
        jBSalvar = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPaneParcelas1 = new javax.swing.JScrollPane();

        setClosable(true);
        setTitle("Novo Emprestimo");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do emprestimo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jTCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTClienteKeyPressed(evt);
            }
        });

        jListCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClienteMouseClicked(evt);
            }
        });

        jTComissaoColaborador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTComissaoColaborador.setForeground(new java.awt.Color(255, 255, 255));
        jTComissaoColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTComissaoColaboradorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("% Comissão");

        jTValorEmprestar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTValorEmprestar.setForeground(new java.awt.Color(255, 255, 255));
        jTValorEmprestar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTValorEmprestarFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Data lançamento");

        jTPagamentoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTPagamentoTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTPagamentoTotal.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("R$ Valor total");

        jTLucro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTLucro.setForeground(new java.awt.Color(255, 255, 255));
        jTLucro.setEnabled(false);
        jTLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTLucroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("R$ Lucro ");

        jTQtdParcela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTQtdParcela.setForeground(new java.awt.Color(255, 255, 255));
        jTQtdParcela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTQtdParcelaFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Qtd. parcelas");

        jTdataLacamento.setBackground(new java.awt.Color(255, 255, 255));
        jTdataLacamento.setForeground(new java.awt.Color(255, 255, 255));
        jTdataLacamento.setDateFormatString("dd/MM/yyyy");
        jTdataLacamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTdataLacamento.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("R$ Valor ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("% Juros");

        jTjuros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTjuros.setForeground(new java.awt.Color(255, 255, 255));
        jTjuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTjurosFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("R$ Valor Parc.");

        jTCobrador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTCobrador.setForeground(new java.awt.Color(255, 255, 255));
        jTCobrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCobradorKeyPressed(evt);
            }
        });

        jListCobrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListCobrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListCobrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListCobrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCobradorMouseClicked(evt);
            }
        });

        buttonGroupVencimneto.add(jCheckDiario);
        jCheckDiario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckDiario.setText("Diário");
        jCheckDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckDiarioMouseClicked(evt);
            }
        });
        jCheckDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDiarioActionPerformed(evt);
            }
        });

        buttonGroupVencimneto.add(jCheckSemanal);
        jCheckSemanal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckSemanal.setText("Semanal");

        buttonGroupVencimneto.add(jCheckQuinzenal);
        jCheckQuinzenal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckQuinzenal.setText("Quinzenal");
        jCheckQuinzenal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckQuinzenalActionPerformed(evt);
            }
        });

        buttonGroupVencimneto.add(jCheckMensal);
        jCheckMensal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckMensal.setText("Mensal");
        jCheckMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMensalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("R$ Juros díario  ");

        jTvalorJurosDiario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTvalorJurosDiario.setForeground(new java.awt.Color(255, 255, 255));
        jTvalorJurosDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalorJurosDiarioActionPerformed(evt);
            }
        });

        jTValorParcela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTValorParcela.setForeground(new java.awt.Color(255, 255, 255));
        jTValorParcela.setEnabled(false);

        jBGerarParcela.setBackground(new java.awt.Color(51, 51, 51));
        jBGerarParcela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBGerarParcela.setForeground(new java.awt.Color(255, 255, 255));
        jBGerarParcela.setText("Gerar parcelas");
        jBGerarParcela.setBorderPainted(false);
        jBGerarParcela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBGerarParcela.setFocusPainted(false);
        jBGerarParcela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBGerarParcelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBGerarParcelaMouseExited(evt);
            }
        });
        jBGerarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarParcelaActionPerformed(evt);
            }
        });

        buttonGroup1.add(tipoSegundaSexta);
        tipoSegundaSexta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tipoSegundaSexta.setText("Segunda á sexta");

        buttonGroup1.add(tipoSegundaSabado);
        tipoSegundaSabado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tipoSegundaSabado.setText("Segunda á sábado");

        buttonGroup1.add(tipoSegundaSegunda);
        tipoSegundaSegunda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tipoSegundaSegunda.setText("Segunda á segunda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckMensal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jListCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGerarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTValorEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTjuros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTPagamentoTotal)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTLucro)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTQtdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckDiario))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTdataLacamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jListCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckQuinzenal)
                                    .addComponent(jCheckSemanal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoSegundaSexta)
                                    .addComponent(tipoSegundaSegunda)
                                    .addComponent(tipoSegundaSabado))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTvalorJurosDiario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTComissaoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jListCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jTLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(jTValorEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTPagamentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jTjuros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(27, 27, 27))))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(2, 2, 2)
                        .addComponent(jTdataLacamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTQtdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckDiario)
                            .addComponent(tipoSegundaSexta))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jCheckSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jCheckQuinzenal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(tipoSegundaSabado)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckMensal)
                            .addComponent(tipoSegundaSegunda))
                        .addGap(10, 10, 10)
                        .addComponent(jTCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(jTvalorJurosDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jTComissaoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBGerarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jTCliente.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jScrollPaneParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneParcelas)
                .addContainerGap())
        );

        jBSalvar.setBackground(new java.awt.Color(51, 51, 51));
        jBSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBSalvar.setText("Salvar");
        jBSalvar.setBorderPainted(false);
        jBSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBSalvar.setFocusPainted(false);
        jBSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSalvarMouseExited(evt);
            }
        });
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))))
        );

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Novo Emprestimo");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jScrollPaneParcelas1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneParcelas1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneParcelas1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteKeyPressed

        String tam = jTCliente.getText();

        if (jTCliente.getText().isEmpty()) {
            jListCliente.setVisible(false);
        } else if (tam.length() > 5) {
            ListaPesquisa("CLIENTE");
        }
    }//GEN-LAST:event_jTClienteKeyPressed

    private void jListClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClienteMouseClicked
        inserirCliente("CLIENTE");
        jListCliente.setVisible(false);
    }//GEN-LAST:event_jListClienteMouseClicked

    private void jTCobradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCobradorKeyPressed

        String tam = jTCobrador.getText();

        if (jTCobrador.getText().isEmpty()) {
            jListCobrador.setVisible(false);
        } else if (tam.length() > 5) {
            ListaPesquisa("COLABORADOR");
        }
    }//GEN-LAST:event_jTCobradorKeyPressed

    private void jListCobradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCobradorMouseClicked
        inserirCliente("COLABORADOR");
        jListCobrador.setVisible(false);
    }//GEN-LAST:event_jListCobradorMouseClicked

    private void jTvalorJurosDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalorJurosDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalorJurosDiarioActionPerformed

    private void jCheckDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckDiarioMouseClicked

    }//GEN-LAST:event_jCheckDiarioMouseClicked

    private void jTValorEmprestarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTValorEmprestarFocusLost
        calcularTotal();
    }//GEN-LAST:event_jTValorEmprestarFocusLost

    private void jTjurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTjurosFocusLost
        calcularTotal();


    }//GEN-LAST:event_jTjurosFocusLost

    private void jTQtdParcelaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTQtdParcelaFocusLost
        Double totalPagar = ((JDecimalTextField) jTPagamentoTotal).getDoubleValue();
        Double qtdParcelas = ((JDecimalTextField) jTQtdParcela).getDoubleValue();
        ((JDecimalTextField) jTValorParcela).setDoubleValue(totalPagar / qtdParcelas);


    }//GEN-LAST:event_jTQtdParcelaFocusLost

    private void jTComissaoColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTComissaoColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTComissaoColaboradorActionPerformed

    private void jTLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTLucroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTLucroActionPerformed

    private void jBGerarParcelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGerarParcelaMouseEntered
        jBGerarParcela.setBackground(new Color(153, 153, 0));
        jBGerarParcela.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBGerarParcelaMouseEntered

    private void jBGerarParcelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGerarParcelaMouseExited
        jBGerarParcela.setBackground(new Color(51, 51, 51));
        jBGerarParcela.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBGerarParcelaMouseExited

    private void jBGerarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarParcelaActionPerformed
        if (!validaCampos()) {
            JOptionPane.showMessageDialog(null, erros, "Campo Obrigatórios", WIDTH);

        } else {
            addParcela();

        }
    }//GEN-LAST:event_jBGerarParcelaActionPerformed

    private void jBSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalvarMouseEntered
        jBSalvar.setBackground(new Color(153, 153, 0));
        jBSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBSalvarMouseEntered

    private void jBSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalvarMouseExited
        jBSalvar.setBackground(new Color(51, 51, 51));
        jBSalvar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBSalvarMouseExited

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        if (!validaCampos()) {
            JOptionPane.showMessageDialog(null, erros, "Campo Obrigatórios", WIDTH);

        } else if (parcelas == null) {
            JOptionPane.showMessageDialog(null, "Gere pelo menos uma parcela", "Campo Obrigatorio", WIDTH);

        } else {

            criarEmprestimo();
        }


    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jCheckQuinzenalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckQuinzenalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckQuinzenalActionPerformed

    private void jCheckMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckMensalActionPerformed

    private void jCheckDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckDiarioActionPerformed

    private void ListaPesquisa(String modeloPesquisa) {
        modelo = new DefaultListModel();
        modelo.removeAllElements();

        if (modeloPesquisa.equals("CLIENTE")) {
            clienteList = Repository.getInstance().buscarClienteNome(jTCliente.getText());
            if ((clienteList != null) && (!clienteList.isEmpty())) {
                for (Rm_Cliente c : clienteList) {
                    modelo.addElement(c.getNome());

                }
                jListCliente.setModel(modelo);
                jListCliente.setVisible(true);
            }
        } else if (modeloPesquisa.equals("COLABORADOR")) {

            colaboradorList = Repository.getInstance().buscarColaboradorNome(jTCobrador.getText());

            if ((colaboradorList != null) && (!colaboradorList.isEmpty())) {
                for (Rm_Colaborador c : colaboradorList) {
                    modelo.addElement(c.getNome());

                }
                jListCobrador.setModel(modelo);
                jListCobrador.setVisible(true);
            }
        }

    }

    private void inserirCliente(String modeloInserir) {
        if (modeloInserir.equals("CLIENTE")) {
            int linha = jListCliente.getSelectedIndex();
            for (Rm_Cliente c : clienteList) {
                if (c.getNome().equals(modelo.getElementAt(linha))) {
                    cliente = c;

                }
            }
            jTCliente.setText(cliente.getNome());
        }
        if (modeloInserir.equals("COLABORADOR")) {
            int linha = jListCobrador.getSelectedIndex();
            for (Rm_Colaborador c : colaboradorList) {
                if (c.getNome().equals(modelo.getElementAt(linha))) {
                    colaborador = c;

                }
            }
            jTCobrador.setText(colaborador.getNome());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupVencimneto;
    private javax.swing.JButton jBGerarParcela;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JCheckBox jCheckDiario;
    private javax.swing.JCheckBox jCheckMensal;
    private javax.swing.JCheckBox jCheckQuinzenal;
    private javax.swing.JCheckBox jCheckSemanal;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListCliente;
    private javax.swing.JList<String> jListCobrador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPaneParcelas;
    private javax.swing.JScrollPane jScrollPaneParcelas1;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTCobrador;
    private javax.swing.JTextField jTComissaoColaborador;
    private javax.swing.JTextField jTLucro;
    private javax.swing.JTextField jTPagamentoTotal;
    private javax.swing.JTextField jTQtdParcela;
    private javax.swing.JTextField jTValorEmprestar;
    private javax.swing.JTextField jTValorParcela;
    private com.toedter.calendar.JDateChooser jTdataLacamento;
    private javax.swing.JTextField jTjuros;
    private javax.swing.JTextField jTvalorJurosDiario;
    private javax.swing.JCheckBox tipoSegundaSabado;
    private javax.swing.JCheckBox tipoSegundaSegunda;
    private javax.swing.JCheckBox tipoSegundaSexta;
    // End of variables declaration//GEN-END:variables

    private void calcularTotal() {
        //total a pagar
        Double total = ((JDecimalTextField) jTjuros).getDoubleValue();
        Double valorEmprestado = ((JDecimalTextField) jTValorEmprestar).getDoubleValue();
        ((JDecimalTextField) jTPagamentoTotal).setDoubleValue(valorEmprestado + (valorEmprestado * total) / 100);

        //lucro
        ((JDecimalTextField) jTLucro).setDoubleValue((valorEmprestado * total) / 100);
    }

    private void criarTabela() {
        try {

            ArrayList<JBeanTableColumn> columns = new ArrayList<>();
            columns.add(new JBeanTableColumn("numeroParcela", "Numero", true, false, 55, null, null, null));
            columns.add(new JBeanTableColumn("status", "Status", true, false, 140, null, null, null));
            columns.add(new JBeanTableColumn("dataFormatada", "Vencimento", true, false, 100, null, null, null));
            columns.add(new JBeanTableColumn("valor", "Valor", true, false, 120, JDecimalTableCellEditor.class, JDecimalTableCellRenderer.class, null));

            this.jBTParcelas = new JBeanTable(Rm_Parcela.class, columns);
            this.jScrollPaneParcelas.setViewportView(this.jBTParcelas);
        } catch (InstantiationException | IllegalAccessException | IllegalArgumentException ex) {
            Logger.getLogger(NovoEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private boolean validaCampos() {
        erros = new StringBuilder();
        if (jTCliente.getText().trim().isEmpty()) {
            erros.append("Campo CLIENTE Obrigatório \n");
        }
        if (jTValorEmprestar.getText().trim().isEmpty()) {
            erros.append("Campo VALOR DO EMPRÉTIMO é Obrigatório \n");
        }
        if (jTjuros.getText().trim().isEmpty()) {
            erros.append("Campo JÚROS é Obrigatório \n");
        }
        if (jTdataLacamento.getDate() == null) {
            erros.append("Campo Data Lançamento é Obrigatório \n");
        }
        if (colaborador == null) {
            erros.append("Selecione um Cobrador \n");
        }

        if (erros.length() <= 0) {
            return true;
        } else {

            return false;
        }

    }

    public List<Rm_Parcela> criarParcela(List<Date> listaVencimentos) {

        parcelas = new ArrayList<>();
        for (int i = 0; i < listaVencimentos.size(); i++) {
            Rm_Parcela parcela = new Rm_Parcela();
            parcela.setDataVencimento(listaVencimentos.get(i));
            parcela.setNumeroParcela(i + 1);
            parcela.setValor(((JDecimalTextField) jTValorParcela).getDoubleValue());
            parcela.setDataPagamento(null);
            parcela.setStatus("ABERTA");
            parcela.setTaxaJurosDiaria(((JDecimalTextField) jTvalorJurosDiario).getDoubleValue());
            parcela.setValorJurosDiarioRecebido(0d);
            parcela.setValorRecebido(0d);
            parcela.setValorJurosDiario(0d);
            parcelas.add(parcela);
        }

        return parcelas;
    }

    private int getVencimentoSelecionado() {
        if (jCheckDiario.isSelected()) {
            return 1;
        }
        if (jCheckQuinzenal.isSelected()) {
            return 15;
        }
        if (jCheckSemanal.isSelected()) {
            return 7;

        }
        if (jCheckMensal.isSelected()) {
            return 30;
        }
        return 0;
    }

    private String getTipoEmprestimo() {
        if (jCheckDiario.isSelected()) {
            return "DIARIO";
        }
        if (jCheckQuinzenal.isSelected()) {
            return "QUINZENAL";
        }
        if (jCheckSemanal.isSelected()) {
            return "SEMANAL";

        }
        if (jCheckMensal.isSelected()) {
            return "MENSAL";
        }
        return " ";
    }

    private void addParcela() {
        try {
            int intervaloDia = getVencimentoSelecionado();
            ParcelasUtil parcela = new ParcelasUtil();
            double qtdParcela = ((JDecimalTextField) jTQtdParcela).getDoubleValue();

            List<Date> datas = parcela.calcularParcelas(jTdataLacamento.getDate(), intervaloDia, (int) qtdParcela, getTipoVencimento());
            criarParcela(datas);
            jBTParcelas.removeAll();

            jBTParcelas.setModeloDeDados(new ArrayList(parcelas));
        } catch (InstantiationException | IllegalAccessException | NoSuchMethodException | IllegalArgumentException | InvocationTargetException | NoSuchFieldException ex) {
            Logger.getLogger(NovoEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void criarEmprestimo() {
        Rm_Emprestimo novoEmprestimo = new Rm_Emprestimo();

        cliente.setColaborador(colaborador);
        novoEmprestimo.setCliente(cliente);
        novoEmprestimo.setColaborador(colaborador);
        novoEmprestimo.setDataLacamento(jTdataLacamento.getDate());
        novoEmprestimo.setValorEmprestimo(((JDecimalTextField) jTValorEmprestar).getDoubleValue());
        novoEmprestimo.setQtdParcelas(((JDecimalTextField) jTQtdParcela).getDoubleValue());
        novoEmprestimo.setTaxaJuros(((JDecimalTextField) jTjuros).getDoubleValue());
        novoEmprestimo.setValorTotalPagar(((JDecimalTextField) jTPagamentoTotal).getDoubleValue());
        novoEmprestimo.setLucro(((JDecimalTextField) jTLucro).getDoubleValue());
        novoEmprestimo.setStatus("ABERTO");
        novoEmprestimo.setTipoEmprestimo(getTipoEmprestimo());
        novoEmprestimo.setTaxaJurosMultaAtraso(((JDecimalTextField) jTvalorJurosDiario).getDoubleValue());

        novoEmprestimo.setComissaoCobrador(((JDecimalTextField) jTComissaoColaborador).getDoubleValue());

        for (int i = 0; i < parcelas.size(); i++) {
            parcelas.get(i).setEmprestimo(novoEmprestimo);
        }
        novoEmprestimo.setParcela(parcelas);
        //Salva no banco  
        Repository.getInstance().cadastrarEmprestimo(novoEmprestimo);
        JOptionPane.showMessageDialog(null, "EMPRÉSTIMO CRIADO COM SUCESSO", "Sucesso", WIDTH);
        limpar();
    }

    private void limpar() {
        jBTParcelas.removeAll();
        jTCliente.setText("");
        jTCobrador.setText("");
        ((JDecimalTextField) jTjuros).setDoubleValue(0.0);
        ((JDecimalTextField) jTValorEmprestar).setDoubleValue(0.0);
        ((JDecimalTextField) jTPagamentoTotal).setDoubleValue(0.0);
        ((JDecimalTextField) jTQtdParcela).setDoubleValue(0.0);
        ((JDecimalTextField) jTValorParcela).setDoubleValue(0.0);
        ((JDecimalTextField) jTComissaoColaborador).setDoubleValue(0.0);
        ((JDecimalTextField) jTvalorJurosDiario).setDoubleValue(0.0);
        criarTabela();

    }

    private String getTipoVencimento() {
        if (tipoSegundaSexta.isSelected()) {
            return "segunda/sexta";
        }
        if (tipoSegundaSabado.isSelected()) {
            return "segunda/sabado";
        }
        if (tipoSegundaSegunda.isSelected()) {
            return "segunda/segunda";

        }

        return " ";
    }
}
